import { CoinBaseInfo } from "../models/Coin";

export const coninsBaseInfo: CoinBaseInfo[] = [
   { id: 1, name: "Bitcoin", symbol: "BTC" },
   { id: 2, name: "Ethereum", symbol: "ETH" },
   { id: 8, name: "Tether USD", symbol: "USDT" },
   { id: 9, name: "Cardano", symbol: "ADA" },
   { id: 71983, name: "Polkadot", symbol: "DOT***" },
   { id: 3, name: "XRP", symbol: "XRP" },
   { id: 14, name: "Binance Coin", symbol: "BNB" },
   { id: 7, name: "Litecoin", symbol: "LTC" },
   { id: 59, name: "Chainlink", symbol: "LINK" },
   { id: 5858, name: "Wrapped Ether", symbol: "WETH" },
   { id: 4, name: "Bitcoin Cash", symbol: "BCH" },
   { id: 20, name: "Dogecoin", symbol: "DOGE" },
   { id: 6, name: "Stellar", symbol: "XLM" },
   { id: 72821, name: "Uniswap", symbol: "UNI***" },
   { id: 5331, name: "HEX", symbol: "HEX" },
   { id: 1760, name: "USDC", symbol: "USDC" },
   { id: 74883, name: "Aave", symbol: "AAVE*" },
   { id: 62458, name: "Terra", symbol: "LUNA*" },
   { id: 10607, name: "Wrapped BTC", symbol: "WBTC***" },
   { id: 4875, name: "Bitcoin SV", symbol: "BSV" },
   { id: 5, name: "EOS", symbol: "EOS" },
   { id: 4966, name: "Cosmos", symbol: "ATOM*" },
   { id: 70974, name: "Avalanche", symbol: "AVAX" },
   { id: 10883, name: "Synthetix Network", symbol: "SNX" },
   { id: 14585, name: "Algorand", symbol: "ALGO" },
   { id: 10, name: "Monero", symbol: "XMR" },
   { id: 12, name: "IOTA", symbol: "MIOTA" },
   { id: 11, name: "TRON", symbol: "TRX" },
   { id: 18, name: "Tezos", symbol: "XTZ" },
   { id: 96, name: "Theta Token", symbol: "THETA" },
   { id: 17, name: "NEM", symbol: "XEM" },
   { id: 15, name: "NEO", symbol: "NEO" },
   { id: 19, name: "VeChain", symbol: "VET" },
   { id: 71, name: "Huobi Token", symbol: "HT" },
   { id: 68905, name: "Solana", symbol: "SOL*" },
   { id: 1524, name: "OKB", symbol: "OKB" },
   { id: 22, name: "Maker", symbol: "MKR" },
   { id: 72103, name: "SUSHI", symbol: "SUSHI" },
   { id: 4303, name: "Celsius Network", symbol: "CEL" },
   { id: 70838, name: "Compound", symbol: "COMP**" },
   { id: 74500, name: "Filecoin", symbol: "FIL" },
   { id: 68589, name: "Dai", symbol: "DAI" },
   { id: 10296, name: "Crypto.com Chain", symbol: "CRO" },
   { id: 62569, name: "FTX Token", symbol: "FTT**" },
   { id: 14066, name: "BUSD ", symbol: "BUSD" },
   { id: 69380, name: "UMA", symbol: "UMA" },
   { id: 13, name: "Dash", symbol: "DASH" },
   { id: 71246, name: "yearn.finance", symbol: "YFI" },
   { id: 21, name: "Zcash", symbol: "ZEC" },
   { id: 14755, name: "LEO", symbol: "LEO*" }
]